version: '2.4'

services:
  mysql:
    image: mysql:5.7.25
    container_name: ermac_panel_mysql
    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - "3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - ermac_panel

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: ermac_docker_php
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./backend/:/var/www:rw,cached
      - /var/www/storage/
      - /var/www/bootstrap/cache/
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    networks:
      - ermac_panel

  frontend:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: ermac_docker_frontend
    volumes:
      - ./frontend:/var/www:rw,cached
    networks:
      - ermac_panel

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: ermac_docker_nginx
    container_name: ermac_panel_nginx
    restart: unless-stopped
    volumes:
      - ./backend/public:/var/www/public:ro
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./docker/nginx/log/:/var/log/nginx/
    ports:
      - '${BACKEND_INTERFACE}:${BACKEND_PORT}:80'
    networks:
      - ermac_panel

  nginx_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: ermac_docker_nginx_frontend
    container_name: ermac_panel_nginx_frontend
    restart: unless-stopped
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./docker/nginx/frontend.conf.d/:/etc/nginx/conf.d:ro
    ports:
      - '${FRONTEND_INTERFACE}:${FRONTEND_PORT}:80'
    networks:
      - ermac_panel

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ermac_panel_myadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: ermac_panel_mysql
      PMA_ABSOLUTE_URI: /myadmin/
      UPLOAD_LIMIT: 512M
    networks:
      - ermac_panel

  golang:
    build:
      context: .
      dockerfile: Dockerfile.golang
    container_name: ermac_golang
    volumes:
      - ./golang/:/app:rw,cached
    ports:
      - "${GOLANG_PORT}:3434"
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - ermac_panel
networks:
  ermac_panel:
